import { connectDB } from "../src/lib/mongodb";
import Car from "../src/models/Car";

const cars = [
  {
    make: "Alfa Romeo",
    modelName: "Giulia",
    year: 2024,
    transmission: "Otomatik",
    fuelType: "Benzin",
    seats: 5,
    doors: 4,
    pricePerDay: 3200,
    description:
      "İtalyan tutkusu performansla buluşuyor. Alfa Romeo Giulia; etkileyici tasarımı, hassas yol tutuşu ve sürüş keyfi sunar.",
    features: [
      "Spor Modu",
      "Harman Kardon Ses Sistemi",
      "Deri Spor Koltuklar",
      "Çift Bölgeli Klima",
      "Apple CarPlay",
      "Aktif Süspansiyon",
      "Performans Egzozu",
    ],
    location: "Miami",
    isAvailable: true,
    averageRating: 4.5,
    totalReviews: 63,
    mileage: 13400,
    color: "Rosso Kırmızı",
    licensePlate: "FL-ALFA9",
    carType: "Sedan",
  },
  {
    make: "BMW",
    modelName: "X5",
    year: 2023,
    transmission: "Otomatik",
    fuelType: "Dizel",
    seats: 7,
    doors: 5,
    pricePerDay: 4500,
    description:
      "Lüks ve performansın mükemmel birleşimi. BMW X5; geniş iç hacmi, güçlü dizel motoru ve üstün yol tutuşuyla ailenizin yeni gözdesi.",
    features: [
      "Panoramik Cam Tavan",
      "Isıtmalı Koltuklar",
      "Adaptif Cruise Control",
      "Şeritte Kalma Asistanı",
      "Harman Kardon Ses Sistemi",
      "360 Derece Kamera",
    ],
    location: "Istanbul",
    isAvailable: true,
    averageRating: 4.8,
    totalReviews: 128,
    mileage: 28500,
    color: "Alpine Beyaz",
    licensePlate: "34-BMW-05",
    carType: "SUV",
  },
  {
    make: "Tesla",
    modelName: "Model 3",
    year: 2024,
    transmission: "Otomatik",
    fuelType: "Elektrik",
    seats: 5,
    doors: 4,
    pricePerDay: 2800,
    description:
      "Geleceğin sürüşü bugünden. Tesla Model 3; tam elektrikli motoru, otopilot özellikleri ve minimalist iç tasarımıyla teknolojinin zirvesi.",
    features: [
      "Otopilot",
      "15 inç Dokunmatik Ekran",
      "Premium Ses Sistemi",
      "Cam Tavan",
      "Hızlı Şarj",
      "Over-the-Air Güncellemeler",
    ],
    location: "Ankara",
    isAvailable: true,
    averageRating: 4.7,
    totalReviews: 94,
    mileage: 8900,
    color: "Midnight Silver",
    licensePlate: "06-TSL-03",
    carType: "Sedan",
  },
  {
    make: "Toyota",
    modelName: "Corolla",
    year: 2023,
    transmission: "Otomatik",
    fuelType: "Hibrit",
    seats: 5,
    doors: 4,
    pricePerDay: 1450,
    description:
      "Ekonomik ve çevreci bir seçim. Toyota Corolla Hibrit; düşük yakıt tüketimi, güvenilirliği ve konforuyla şehir içi kullanımın vazgeçilmezi.",
    features: [
      "Hibrit Sürüş Modları",
      "Toyota Safety Sense",
      "Geri Görüş Kamerası",
      "Bluetooth",
      "Otomatik Klima",
      "Şerit Takip Sistemi",
    ],
    location: "Izmir",
    isAvailable: true,
    averageRating: 4.4,
    totalReviews: 211,
    mileage: 42100,
    color: "Gümüş Gri",
    licensePlate: "35-TYT-23",
    carType: "Hatchback",
  },
  {
    make: "Porsche",
    modelName: "911 Carrera",
    year: 2024,
    transmission: "Yarı Otomatik",
    fuelType: "Benzin",
    seats: 4,
    doors: 2,
    pricePerDay: 8900,
    description:
      "Efsanevi bir spor otomobil deneyimi. Porsche 911 Carrera; ikonik tasarımı, baş döndürücü performansı ve eşsiz sürüş hissiyatıyla bir başyapıt.",
    features: [
      "Sport Chrono Paketi",
      "PDK Şanzıman",
      "BOSE Ses Sistemi",
      "Adaptif Spor Koltuklar",
      "Launch Control",
      "Karbon Seramik Frenler",
    ],
    location: "Bodrum",
    isAvailable: true,
    averageRating: 4.9,
    totalReviews: 47,
    mileage: 5600,
    color: "Guards Kırmızı",
    licensePlate: "48-PRS-11",
    carType: "Coupe",
  },
  {
    make: "Volkswagen",
    modelName: "Golf",
    year: 2023,
    transmission: "Manuel",
    fuelType: "Benzin",
    seats: 5,
    doors: 5,
    pricePerDay: 1100,
    description:
      "Avrupa'nın en çok tercih edilen otomobillerinden biri. Volkswagen Golf; dengeli sürüş dinamikleri, geniş iç mekanı ve güvenilirliğiyle her yolculukta yanınızda.",
    features: [
      "Geri Görüş Kamerası",
      "Apple CarPlay & Android Auto",
      "Otomatik Klima",
      "Şerit Koruma Sistemi",
      "LED Far",
      "Dijital Gösterge Paneli",
    ],
    location: "Istanbul",
    isAvailable: true,
    averageRating: 4.3,
    totalReviews: 187,
    mileage: 31200,
    color: "Derin Siyah",
    licensePlate: "34-VWG-20",
    carType: "Hatchback",
  },
  {
    make: "Renault",
    modelName: "Clio",
    year: 2022,
    transmission: "Manuel",
    fuelType: "Benzin",
    seats: 5,
    doors: 5,
    pricePerDay: 850,
    description:
      "Şehrin kalabalık sokaklarında manevra kabiliyeti yüksek, ekonomik ve pratik bir tercih. Renault Clio ile şehir sürüşü keyfe dönüşür.",
    features: ["Bluetooth Ses Sistemi", "Geri Görüş Kamerası", "Manuel Klima", "USB Şarj", "Merkezi Kilit"],
    location: "Izmir",
    isAvailable: true,
    averageRating: 4.1,
    totalReviews: 256,
    mileage: 54800,
    color: "Flamme Turuncu",
    licensePlate: "35-RNO-22",
    carType: "Hatchback",
  },
  {
    make: "Ford",
    modelName: "Focus",
    year: 2022,
    transmission: "Otomatik",
    fuelType: "Benzin",
    seats: 5,
    doors: 4,
    pricePerDay: 1200,
    description:
      "Sürüş zevkini ön plana çıkaran kompakt bir sedan. Ford Focus; cevap veren direksiyon hissi ve konforlu süspansiyonuyla uzun yolculuklarda bile yorulmaz.",
    features: [
      "Ford SYNC Navigasyon",
      "Geri Görüş Kamerası",
      "Çift Bölgeli Klima",
      "Apple CarPlay",
      "Ön Çarpışma Uyarısı",
    ],
    location: "Ankara",
    isAvailable: true,
    averageRating: 4.2,
    totalReviews: 143,
    mileage: 39700,
    color: "Frozen Beyaz",
    licensePlate: "06-FRD-22",
    carType: "Sedan",
  },
  {
    make: "Honda",
    modelName: "Civic",
    year: 2023,
    transmission: "Otomatik",
    fuelType: "Benzin",
    seats: 5,
    doors: 4,
    pricePerDay: 1350,
    description:
      "On yıllardır güvenilirliğiyle öne çıkan bir sınıf ikonu. Honda Civic; modern iç tasarımı, ekonomik yakıt tüketimi ve zengin güvenlik donanımıyla öne çıkıyor.",
    features: [
      "Honda Sensing Paket",
      "10.2 inç Dokunmatik Ekran",
      "Otomatik Klima",
      "Geri Görüş Kamerası",
      "Kablosuz Apple CarPlay",
      "Uyarlamalı Cruise Control",
    ],
    location: "Antalya",
    isAvailable: true,
    averageRating: 4.4,
    totalReviews: 172,
    mileage: 22300,
    color: "Sonic Gri",
    licensePlate: "07-HND-23",
    carType: "Sedan",
  },
  {
    make: "Dacia",
    modelName: "Duster",
    year: 2023,
    transmission: "Manuel",
    fuelType: "Dizel",
    seats: 5,
    doors: 5,
    pricePerDay: 980,
    description:
      "Her bütçeye uygun, sağlam yapısıyla ön plana çıkan SUV. Dacia Duster; yüksek arazi kabiliyeti ve geniş bagajıyla macera tutkunlarının vazgeçilmezi.",
    features: ["4x4 Sürüş Sistemi", "Geri Görüş Kamerası", "MediaNav Navigasyon", "Manuel Klima", "Dağ İnişi Kontrolü"],
    location: "Trabzon",
    isAvailable: true,
    averageRating: 4.0,
    totalReviews: 98,
    mileage: 47500,
    color: "Slate Gri",
    licensePlate: "61-DCA-23",
    carType: "SUV",
  },
  {
    make: "Hyundai",
    modelName: "i20",
    year: 2023,
    transmission: "Otomatik",
    fuelType: "Benzin",
    seats: 5,
    doors: 5,
    pricePerDay: 920,
    description:
      "Kompakt boyutu ve şık tasarımıyla şehir içinde çevik, uzun yolda konforlu. Hyundai i20 her sürücüye hitap eden dengeli bir tercih.",
    features: [
      "10.25 inç Dokunmatik Ekran",
      "Geri Görüş Kamerası",
      "Otomatik Klima",
      "Bluetooth",
      "Akıllı Hız Limiti Okuma",
    ],
    location: "Bursa",
    isAvailable: true,
    averageRating: 4.2,
    totalReviews: 119,
    mileage: 18600,
    color: "Phantom Siyah",
    licensePlate: "16-HYN-23",
    carType: "Hatchback",
  },
  {
    make: "Mercedes-Benz",
    modelName: "C 200",
    year: 2023,
    transmission: "Otomatik",
    fuelType: "Benzin",
    seats: 5,
    doors: 4,
    pricePerDay: 3800,
    description:
      "Lüks ve teknolojinin mükemmel dengesi. Mercedes-Benz C 200; yeni nesil MBUX sistemi, premium iç mekanı ve süpürgelik konforuyla iş seyahatlerinin baş tacı.",
    features: [
      "MBUX Ses Kontrol Sistemi",
      "Isıtmalı Ön Koltuklar",
      "Panoramik Cam Tavan",
      "360 Derece Kamera",
      "Aktif Frenleme",
      "Kablosuz Şarj",
    ],
    location: "Istanbul",
    isAvailable: true,
    averageRating: 4.7,
    totalReviews: 89,
    mileage: 17400,
    color: "Obsidian Siyah",
    licensePlate: "34-MBZ-23",
    carType: "Sedan",
  },
  {
    make: "Toyota",
    modelName: "Land Cruiser",
    year: 2024,
    transmission: "Otomatik",
    fuelType: "Dizel",
    seats: 7,
    doors: 5,
    pricePerDay: 5500,
    description:
      "Her zeminde hâkim, her koşulda güvenilir. Toyota Land Cruiser; efsanevi arazi kabiliyeti ve geniş kabin konforu ile sizi sınırsız maceraya davet ediyor.",
    features: [
      "Multi-Terrain Select",
      "Crawl Control",
      "Panoramik Cam Tavan",
      "Isıtmalı/Soğutmalı Koltuklar",
      "JBL Premium Ses Sistemi",
      "360 Derece Kamera",
      "Haval Basıncı İzleme",
    ],
    location: "Erzurum",
    isAvailable: true,
    averageRating: 4.8,
    totalReviews: 61,
    mileage: 19800,
    color: "Pearl Beyaz",
    licensePlate: "25-TLC-24",
    carType: "SUV",
  },
  {
    make: "Lamborghini",
    modelName: "Huracán EVO",
    year: 2023,
    transmission: "Yarı Otomatik",
    fuelType: "Benzin",
    seats: 2,
    doors: 2,
    pricePerDay: 18500,
    description:
      "Saf adrenalin. Lamborghini Huracán EVO; 640 beygirlik V10 motoruyla 0-100 km/s'yi 2.9 saniyede geçer ve her köşede sürücüsünü hayrete düşürür.",
    features: [
      "LDVI Dinamik Vektör Yönetimi",
      "Magneto-Reolojik Süspansiyon",
      "Karbon Seramik Frenler",
      "Titanium Egzoz",
      "Drive Mode Selector",
      "Alcantara İç Döşeme",
    ],
    location: "Miami",
    isAvailable: true,
    averageRating: 5.0,
    totalReviews: 18,
    mileage: 3200,
    color: "Arancio Borealis",
    licensePlate: "FL-LAMB3",
    carType: "Coupe",
  },
  {
    make: "Ferrari",
    modelName: "Roma",
    year: 2024,
    transmission: "Yarı Otomatik",
    fuelType: "Benzin",
    seats: 4,
    doors: 2,
    pricePerDay: 22000,
    description:
      "İtalyan zarifliğinin en saf hali. Ferrari Roma; 620 beygirlik twin-turbo V8 motoru, büyüleyici grand tourer tasarımı ve eşsiz sürüş deneyimiyle lüksü yeniden tanımlıyor.",
    features: [
      "Ferrari Side Slip Control",
      "Manettino Direksiyon Kumandası",
      "JBL Professionel Ses Sistemi",
      "Karbon Fiber Trim",
      "Çift Katmanlı Cam Tavan",
      "Kişiselleştirilebilir Sürüş Modları",
    ],
    location: "Bodrum",
    isAvailable: false,
    averageRating: 5.0,
    totalReviews: 11,
    mileage: 2100,
    color: "Rosso Portofino",
    licensePlate: "48-FRR-24",
    carType: "Coupe",
  },
  {
    make: "Bugatti",
    modelName: "Chiron",
    year: 2022,
    transmission: "Yarı Otomatik",
    fuelType: "Benzin",
    seats: 2,
    doors: 2,
    pricePerDay: 75000,
    description:
      "Otomobil mühendisliğinin zirvesi. Bugatti Chiron; 1500 beygirlik quad-turbo W16 motoruyla üretilen en hızlı ve en pahalı yol arabalarından biridir. Deneyimleyecek misiniz?",
    features: [
      "W16 Quad-Turbo Motor",
      "Karbon Monokok Gövde",
      "Aktif Aerodinamik",
      "Özel Michelin Pilot Sport Lastikler",
      "El Yapımı Deri İç Mekan",
      "Titanyum Egzoz Sistemi",
    ],
    location: "Miami",
    isAvailable: true,
    averageRating: 5.0,
    totalReviews: 4,
    mileage: 1800,
    color: "French Racing Blue",
    licensePlate: "FL-BGT16",
    carType: "Coupe",
  },
  {
    make: "Rolls-Royce",
    modelName: "Ghost",
    year: 2024,
    transmission: "Otomatik",
    fuelType: "Benzin",
    seats: 5,
    doors: 4,
    pricePerDay: 28000,
    description:
      "Sessizliğin ve lüksün sembolü. Rolls-Royce Ghost; el işçiliğiyle hazırlanmış iç mekanı, yıldızlı tavan seçeneği ve neredeyse sessiz sürüşüyle gerçek anlamda ayrıcalığı sunar.",
    features: [
      "Starlight Headliner (Yıldızlı Tavan)",
      "Planar Süspansiyon",
      "Bespoke Ses Sistemi",
      "Masaj Koltuğu",
      "Soğutmalı Arka Koltuklar",
      "Spirit of Ecstasy Mascot",
    ],
    location: "Istanbul",
    isAvailable: true,
    averageRating: 4.9,
    totalReviews: 9,
    mileage: 4300,
    color: "Angora Beyaz",
    licensePlate: "34-RRG-24",
    carType: "Sedan",
  },
  {
    make: "McLaren",
    modelName: "720S",
    year: 2023,
    transmission: "Yarı Otomatik",
    fuelType: "Benzin",
    seats: 2,
    doors: 2,
    pricePerDay: 19500,
    description:
      "Aerodinamiğin sanata dönüştüğü an. McLaren 720S; 720 beygirlik twin-turbo V8 ile 0-100'ü 2.8 saniyede geçen, karbon fiber gövdesiyle yolda bir heykel.",
    features: [
      "Aktif Dinamik Egzoz",
      "Pro Aktif Şasi Kontrol",
      "Karbon Fiber Monosel",
      "Dihedral Kapılar",
      "Track Telemetri Sistemi",
      "Özel McLaren Ses Sistemi",
    ],
    location: "Bodrum",
    isAvailable: true,
    averageRating: 4.9,
    totalReviews: 22,
    mileage: 6700,
    color: "Papaya Turuncu",
    licensePlate: "48-MCL-23",
    carType: "Coupe",
  },
  {
    make: "Aston Martin",
    modelName: "DB11",
    year: 2023,
    transmission: "Otomatik",
    fuelType: "Benzin",
    seats: 4,
    doors: 2,
    pricePerDay: 15000,
    description:
      "İngiliz zarafetinin doruk noktası. Aston Martin DB11; zarif grand tourer duruşu, güçlü V12 motoru ve ağırlıklı olarak el yapımı iç mekanıyla sporu lüksle harmanlıyor.",
    features: [
      "AMG Twin-Turbo V12",
      "Aeroblade Teknolojisi",
      "Bang & Olufsen BeoSound Ses Sistemi",
      "Nappa Deri İç Mekan",
      "Elektronik Diferansiyel",
      "Dinamik Torque Vektörleme",
    ],
    location: "Istanbul",
    isAvailable: true,
    averageRating: 4.8,
    totalReviews: 27,
    mileage: 9100,
    color: "Onyx Siyah",
    licensePlate: "34-ASM-23",
    carType: "Coupe",
  },
  {
    make: "Jeep",
    modelName: "Wrangler Rubicon",
    year: 2023,
    transmission: "Manuel",
    fuelType: "Benzin",
    seats: 5,
    doors: 4,
    pricePerDay: 2600,
    description:
      "Arazi araçlarının efsanesi. Jeep Wrangler Rubicon; çıkarılabilir kapıları, katlanır camı ve sonsuz modifiye potansiyeliyle off-road tutkunlarının rüyası.",
    features: [
      "Rock-Trac 4x4 Sistemi",
      "Sway Bar Disconnect",
      "Elektronik Diferansiyel Kilidi",
      "Dana 44 Aks",
      "Kaldırılabilir Tavan",
      "Çıkarılabilir Kapılar",
    ],
    location: "Antalya",
    isAvailable: true,
    averageRating: 4.5,
    totalReviews: 74,
    mileage: 23400,
    color: "Firecracker Kırmızı",
    licensePlate: "07-JEP-23",
    carType: "SUV",
  },
  {
    make: "Volkswagen",
    modelName: "Transporter",
    year: 2022,
    transmission: "Otomatik",
    fuelType: "Dizel",
    seats: 9,
    doors: 5,
    pricePerDay: 1800,
    description:
      "Aile gezileri ve grup seyahatleri için ideal. Volkswagen Transporter; geniş ve konfigüre edilebilir kabinüyle hem yolculara hem de bagaja bolca alan sunuyor.",
    features: [
      "Sürgülü Yan Kapılar",
      "Isıtmalı Ön Koltuklar",
      "Navigasyon Sistemi",
      "Klima",
      "Geri Görüş Kamerası",
      "Kör Nokta Uyarı",
    ],
    location: "Istanbul",
    isAvailable: true,
    averageRating: 4.3,
    totalReviews: 105,
    mileage: 61200,
    color: "Candy Beyaz",
    licensePlate: "34-VWT-22",
    carType: "Minivan",
  },
  {
    make: "Koenigsegg",
    modelName: "Jesko",
    year: 2023,
    transmission: "Yarı Otomatik",
    fuelType: "Benzin",
    seats: 2,
    doors: 2,
    pricePerDay: 95000,
    description:
      "Yeryüzündeki en hızlı otomobillerden biri. Koenigsegg Jesko; 1600 beygir gücündeki 5.0L twin-turbo V8'i ve özel LST şanzımanıyla otomobil sınırlarını yeniden çiziyor.",
    features: [
      "LST (Light Speed Transmission)",
      "Aktif Aero Paketi",
      "Triplex Süspansiyon",
      "Karbon Fiber Monokok",
      "Biyometrik Koltuk",
      "Özel Michelin Cup2 Lastikler",
    ],
    location: "Miami",
    isAvailable: false,
    averageRating: 5.0,
    totalReviews: 3,
    mileage: 900,
    color: "Matte Carbon",
    licensePlate: "FL-KSG01",
    carType: "Coupe",
  },
  {
    make: "Peugeot",
    modelName: "3008",
    year: 2023,
    transmission: "Otomatik",
    fuelType: "Hibrit",
    seats: 5,
    doors: 5,
    pricePerDay: 1650,
    description:
      "Fransız tasarım anlayışını modern teknoloji ile birleştiren crossover. Peugeot 3008; i-Cockpit gösterge paneli ve plug-in hibrit seçeneğiyle öne çıkıyor.",
    features: [
      "i-Cockpit Head-Up Display",
      "Plug-In Hibrit Sürüş",
      "Panoramik Cam Tavan",
      "Masaj Ön Koltuklar",
      "Focal Premium Ses Sistemi",
      "Gece Görüş Sistemi",
    ],
    location: "Izmir",
    isAvailable: true,
    averageRating: 4.3,
    totalReviews: 88,
    mileage: 26700,
    color: "Pearl Beyaz",
    licensePlate: "35-PGT-23",
    carType: "SUV",
  },
  {
    make: "Audi",
    modelName: "A4",
    year: 2023,
    transmission: "Otomatik",
    fuelType: "Benzin",
    seats: 5,
    doors: 4,
    pricePerDay: 2900,
    description:
      "Alman mühendisliğinin sembolü. Audi A4; zarif tasarımı, üstün sürüş konforu ve gelişmiş teknolojisiyle executive sedan segmentinin gözdesi.",
    features: [
      "MMI Navigation Plus",
      "Virtual Cockpit",
      "Isıtmalı Ön Koltuklar",
      "Bang & Olufsen Ses Sistemi",
      "Adaptif Cruise Assist",
      "Matrix LED Farlar",
    ],
    location: "Istanbul",
    isAvailable: true,
    averageRating: 4.6,
    totalReviews: 134,
    mileage: 21500,
    color: "Navarra Mavi",
    licensePlate: "34-ADI-23",
    carType: "Sedan",
  },
  {
    make: "Audi",
    modelName: "Q8",
    year: 2024,
    transmission: "Otomatik",
    fuelType: "Hibrit",
    seats: 5,
    doors: 5,
    pricePerDay: 6200,
    description:
      "SUV dünyasının en iddialı isimlerinden biri. Audi Q8; spor coupe silüeti, 48V mild-hybrid sistemi ve quattro kalıcı dört tekerlekten çekişiyle tanımları değiştiriyor.",
    features: [
      "quattro AWD",
      "Hava Süspansiyonu",
      "Panoramik Cam Tavan",
      "Head-Up Display",
      "Çift MMI Dokunmatik Ekran",
      "Isıtmalı/Soğutmalı Koltuklar",
      "Night Vision Assist",
    ],
    location: "Ankara",
    isAvailable: true,
    averageRating: 4.7,
    totalReviews: 52,
    mileage: 14200,
    color: "Mythos Siyah",
    licensePlate: "06-ADQ-24",
    carType: "SUV",
  },
  {
    make: "BMW",
    modelName: "M3 Competition",
    year: 2024,
    transmission: "Otomatik",
    fuelType: "Benzin",
    seats: 5,
    doors: 4,
    pricePerDay: 7800,
    description:
      "Sedan performansının sınırlarını zorlayan bir şaheser. BMW M3 Competition; 510 beygirlik çift turbo altı silindiri ve M xDrive sistemiyle pisti sokağa taşıyor.",
    features: [
      "M xDrive AWD",
      "M Carbon Koltuklar",
      "Launch Control",
      "M Sport Egzoz",
      "Aktif M Diferansiyel",
      "Karbon Seramik Frenler",
      "Harman Kardon Ses",
    ],
    location: "Istanbul",
    isAvailable: true,
    averageRating: 4.9,
    totalReviews: 38,
    mileage: 7300,
    color: "Isle of Man Yeşil",
    licensePlate: "34-BMW-M3",
    carType: "Sedan",
  },
  {
    make: "Mercedes-Benz",
    modelName: "G 63 AMG",
    year: 2024,
    transmission: "Otomatik",
    fuelType: "Benzin",
    seats: 5,
    doors: 5,
    pricePerDay: 12500,
    description:
      "İkonik tasarım, canavar güç. Mercedes-Benz G 63 AMG; 585 beygirlik twin-turbo V8 ile hem kenti hem arazisi yönetir. Statü ve güç bu araçta bir arada.",
    features: [
      "AMG 4MATIC+ AWD",
      "3 Mekanik Diferansiyel Kilidi",
      "Burmester Ses Sistemi",
      "AMG Ride Control Süspansiyon",
      "Isıtmalı/Soğutmalı/Masaj Koltuklar",
      "360 Derece Kamera",
    ],
    location: "Istanbul",
    isAvailable: true,
    averageRating: 4.9,
    totalReviews: 31,
    mileage: 8800,
    color: "Obsidian Siyah",
    licensePlate: "34-GWG-24",
    carType: "SUV",
  },
  {
    make: "Tesla",
    modelName: "Model S Plaid",
    year: 2024,
    transmission: "Otomatik",
    fuelType: "Elektrik",
    seats: 5,
    doors: 4,
    pricePerDay: 8500,
    description:
      "Dünyanın en hızlı üretim sedanı. Tesla Model S Plaid; 1020 beygir gücündeki üç motorlu sistemiyle 0-100 km/s'yi yalnızca 2.1 saniyede geçiyor.",
    features: [
      "Trimotor AWD",
      "17 inç Dokunmatik Ekran",
      "Oyun Bilgisayarı",
      "Tam Öz Sürüş Paketi",
      "Hava Süspansiyonu",
      "HEPA Filtre Sistemi",
      "Over-the-Air Güncellemeler",
    ],
    location: "Ankara",
    isAvailable: true,
    averageRating: 4.8,
    totalReviews: 29,
    mileage: 11200,
    color: "Stealth Grey",
    licensePlate: "06-TSP-24",
    carType: "Sedan",
  },
  {
    make: "Rivian",
    modelName: "R1T",
    year: 2024,
    transmission: "Otomatik",
    fuelType: "Elektrik",
    seats: 5,
    doors: 4,
    pricePerDay: 4800,
    description:
      "Elektrikli pickup'ın öncüsü. Rivian R1T; dört motorlu sistemi, 800+ km menzili ve Gear Tunnel depolama alanıyla off-road ile lüksü birleştiriyor.",
    features: [
      "Quad-Motor AWD",
      "Hava Süspansiyonu",
      "Gear Tunnel Depolama",
      "Camp Speaker",
      "15.6 inç Dokunmatik Ekran",
      "Çadır Entegrasyonu",
    ],
    location: "Miami",
    isAvailable: true,
    averageRating: 4.6,
    totalReviews: 41,
    mileage: 16800,
    color: "Launch Green",
    licensePlate: "FL-RVN24",
    carType: "Pickup",
  },
  {
    make: "Ford",
    modelName: "Mustang GT",
    year: 2023,
    transmission: "Manuel",
    fuelType: "Benzin",
    seats: 4,
    doors: 2,
    pricePerDay: 3500,
    description:
      "Amerikan kas gücünün simgesi. Ford Mustang GT; 460 beygirlik 5.0L Coyote V8 motoru ve ikonik fastback tasarımıyla özgürlüğü temsil ediyor.",
    features: [
      "5.0L Coyote V8",
      "Aktif Egzoz Kontrolü",
      "MagneRide Süspansiyon",
      "SYNC 4 Dokunmatik Ekran",
      "Launch Control",
      "Track Apps",
    ],
    location: "Miami",
    isAvailable: true,
    averageRating: 4.6,
    totalReviews: 83,
    mileage: 18900,
    color: "Race Red",
    licensePlate: "FL-MSTG3",
    carType: "Coupe",
  },
  {
    make: "Chevrolet",
    modelName: "Corvette C8",
    year: 2024,
    transmission: "Otomatik",
    fuelType: "Benzin",
    seats: 2,
    doors: 2,
    pricePerDay: 9200,
    description:
      "Amerikan mühendisliğinin gururu, mid-engine devrim. Chevrolet Corvette C8; 495 beygirlik 6.2L LT2 V8 ile 0-100'ü 2.9 saniyede geçiyor.",
    features: [
      "Mid-Engine LT2 V8",
      "Magnetic Ride Control 4",
      "Performance Data Recorder",
      "Bose Ses Sistemi",
      "GT2 Performans Koltuğu",
      "Front Lift System",
    ],
    location: "Miami",
    isAvailable: true,
    averageRating: 4.8,
    totalReviews: 55,
    mileage: 9400,
    color: "Rapid Blue",
    licensePlate: "FL-CVT-C8",
    carType: "Coupe",
  },
  {
    make: "Bentley",
    modelName: "Continental GT",
    year: 2024,
    transmission: "Otomatik",
    fuelType: "Benzin",
    seats: 4,
    doors: 2,
    pricePerDay: 32000,
    description:
      "Lüks grand touring'in tanımı. Bentley Continental GT; el yapımı iç mekanı, 650 beygirlik W12 motoru ve eşsiz yolculuk konforu ile lüks seyahati yeniden tanımlıyor.",
    features: [
      "6.0L W12 TSI Motor",
      "Naim Ses Sistemi",
      "Döner MMI Gösterge Paneli",
      "Isıtmalı/Soğutmalı/Masaj Koltuklar",
      "Hava Süspansiyonu",
      "El Yapımı Ahşap/Deri Kaplama",
    ],
    location: "Istanbul",
    isAvailable: true,
    averageRating: 4.9,
    totalReviews: 14,
    mileage: 5200,
    color: "Moonbeam Gümüş",
    licensePlate: "34-BNT-24",
    carType: "Coupe",
  },
  {
    make: "Maserati",
    modelName: "Ghibli",
    year: 2023,
    transmission: "Otomatik",
    fuelType: "Benzin",
    seats: 5,
    doors: 4,
    pricePerDay: 6800,
    description:
      "İtalyan ruhunu taşıyan bir spor sedan. Maserati Ghibli; benzersiz egzoz sesi, çarpıcı tasarımı ve Q4 dört tekerlekten çekişiyle sıradan olmayı reddediyor.",
    features: [
      "Q4 AWD Sistemi",
      "Skyhook Süspansiyon",
      "Bowers & Wilkins Ses Sistemi",
      "Maserati Touch Control Plus",
      "Harman Kardon Ses Sistemi",
      "Deri/Alcantara İç Mekan",
    ],
    location: "Bodrum",
    isAvailable: true,
    averageRating: 4.6,
    totalReviews: 33,
    mileage: 14700,
    color: "Blu Emozione",
    licensePlate: "48-MSR-23",
    carType: "Sedan",
  },
  {
    make: "Land Rover",
    modelName: "Range Rover Sport",
    year: 2024,
    transmission: "Otomatik",
    fuelType: "Hibrit",
    seats: 5,
    doors: 5,
    pricePerDay: 7200,
    description:
      "Sportif ruh ile lüks konforun buluşma noktası. Range Rover Sport; güçlü PHEV sistemi ve Terrain Response 2 teknolojisiyle her zeminde hakimiyet kuruyor.",
    features: [
      "Terrain Response 2",
      "Air Suspension",
      "Meridian Ses Sistemi",
      "Panoramik Cam Tavan",
      "Isıtmalı/Soğutmalı Koltuklar",
      "Wading Kamera",
      "Head-Up Display",
    ],
    location: "Istanbul",
    isAvailable: true,
    averageRating: 4.7,
    totalReviews: 46,
    mileage: 12300,
    color: "Carpathian Grey",
    licensePlate: "34-LRR-24",
    carType: "SUV",
  },
  {
    make: "Pagani",
    modelName: "Huayra",
    year: 2022,
    transmission: "Yarı Otomatik",
    fuelType: "Benzin",
    seats: 2,
    doors: 2,
    pricePerDay: 110000,
    description:
      "Sanat ve mühendisliğin birleşimi, dünyada yalnızca 100 adet üretilen efsane. Pagani Huayra; Mercedes-AMG'nin 730 beygirlik V12'si ve tam karbon fiber gövdesiyle otomobilin ötesinde bir deneyim.",
    features: [
      "Mercedes-AMG V12 Bi-Turbo",
      "Aktif Aerodinamik Kanatlar",
      "Karbon Fiber/Titanyum Şasi",
      "El Yapımı Deri Döşeme",
      "Özel Pirelli P Zero Lastikler",
      "Kişiselleştirilmiş Bagaj Seti",
    ],
    location: "Miami",
    isAvailable: false,
    averageRating: 5.0,
    totalReviews: 2,
    mileage: 620,
    color: "Bianco Perla",
    licensePlate: "FL-PGN22",
    carType: "Coupe",
  },
  {
    make: "Nissan",
    modelName: "GT-R",
    year: 2023,
    transmission: "Yarı Otomatik",
    fuelType: "Benzin",
    seats: 4,
    doors: 2,
    pricePerDay: 7500,
    description:
      "Godzilla lakabıyla efsaneleşen performans canavarı. Nissan GT-R; 570 beygirlik twin-turbo V6'sı ve ATTESA all-wheel-drive sistemiyle olağanüstü hız ve kontrol sunuyor.",
    features: [
      "ATTESA E-TS AWD",
      "Bilstein DampTronic Süspansiyon",
      "Bose Ses Sistemi",
      "Launch Control",
      "Karbon Seramik Brembo Frenler",
      "Çift Clutch PDK Şanzıman",
    ],
    location: "Istanbul",
    isAvailable: true,
    averageRating: 4.8,
    totalReviews: 44,
    mileage: 11800,
    color: "Ultimate Metal Silver",
    licensePlate: "34-NSN-GT",
    carType: "Coupe",
  },
  {
    make: "Subaru",
    modelName: "Forester",
    year: 2023,
    transmission: "Otomatik",
    fuelType: "Benzin",
    seats: 5,
    doors: 5,
    pricePerDay: 1550,
    description:
      "Doğa tutkunları için biçilmiş kaftan. Subaru Forester; Symmetrical AWD sistemi ve geniş arka bagajıyla hem şehir hem de dağ yollarında güvenilir bir yoldaş.",
    features: [
      "Symmetrical AWD",
      "EyeSight Sürücü Asistanı",
      "X-Mode Arazi Sistemi",
      "Panoramik Cam Tavan",
      "Geri Görüş Kamerası",
      "Apple CarPlay",
    ],
    location: "Trabzon",
    isAvailable: true,
    averageRating: 4.3,
    totalReviews: 91,
    mileage: 33600,
    color: "Jasper Green",
    licensePlate: "61-SBR-23",
    carType: "SUV",
  },
  {
    make: "Kia",
    modelName: "EV6",
    year: 2024,
    transmission: "Otomatik",
    fuelType: "Elektrik",
    seats: 5,
    doors: 5,
    pricePerDay: 2100,
    description:
      "Elektrikli otomobil tasarımını baştan yazan bir GT. Kia EV6; 800V ultra-hızlı şarj altyapısı, 528 km menzili ve özel GT versiyonuyla sektörün yeni standardını koyuyor.",
    features: [
      "800V Ultra-Hızlı Şarj",
      "Vehicle-to-Load (V2L)",
      "Augmented Reality HUD",
      "Meridian Ses Sistemi",
      "Isıtmalı Ön/Arka Koltuklar",
      "Sürücü Dikkat Uyarı",
    ],
    location: "Ankara",
    isAvailable: true,
    averageRating: 4.5,
    totalReviews: 76,
    mileage: 14500,
    color: "Runway Red",
    licensePlate: "06-KIA-24",
    carType: "Hatchback",
  },
  {
    make: "Volvo",
    modelName: "XC90",
    year: 2024,
    transmission: "Otomatik",
    fuelType: "Hibrit",
    seats: 7,
    doors: 5,
    pricePerDay: 4200,
    description:
      "İskandinav güvenliği ve konforunun doruk noktası. Volvo XC90 Recharge; 455 beygirlik PHEV sistemi, saf ahşap ve deri iç mekanıyla aile SUV'larının şampiyonu.",
    features: [
      "PHEV T8 Twin Engine",
      "Pilot Assist Yarı Otonom Sürüş",
      "Bowers & Wilkins Ses Sistemi",
      "Panoramik Cam Tavan",
      "Hava Süspansiyonu",
      "360 Kamera",
      "İskandinav Tasarım İç Mekan",
    ],
    location: "Istanbul",
    isAvailable: true,
    averageRating: 4.7,
    totalReviews: 67,
    mileage: 19100,
    color: "Crystal White",
    licensePlate: "34-VLV-24",
    carType: "SUV",
  },
  {
    make: "Opel",
    modelName: "Astra",
    year: 2023,
    transmission: "Otomatik",
    fuelType: "Benzin",
    seats: 5,
    doors: 5,
    pricePerDay: 1050,
    description:
      "Alman mühendisliğinin uygun fiyatlı temsilcisi. Opel Astra; kompakt boyutu, modern iç mekanı ve verimli motoruyla günlük kullanımın en akıllı tercihlerinden biri.",
    features: [
      "IntelliLux LED Matrix",
      "Apple CarPlay & Android Auto",
      "Otomatik Klima",
      "Geri Görüş Kamerası",
      "Lane Keep Assist",
      "Kablosuz Şarj",
    ],
    location: "Bursa",
    isAvailable: true,
    averageRating: 4.1,
    totalReviews: 148,
    mileage: 28400,
    color: "Volcanic Rock Gri",
    licensePlate: "16-OPL-23",
    carType: "Hatchback",
  },
  {
    make: "Skoda",
    modelName: "Octavia",
    year: 2023,
    transmission: "Otomatik",
    fuelType: "Dizel",
    seats: 5,
    doors: 5,
    pricePerDay: 1300,
    description:
      "Çek mühendisliğinin pratik dehasının ürünü. Skoda Octavia; Volkswagen altyapısı üzerine kurulu, sınıfının en geniş bagaj hacmine sahip ve tutumlu dizel motoruyla uzun yol şampiyonu.",
    features: [
      "Virtual Cockpit",
      "Canton Ses Sistemi",
      "Tam LED Farlar",
      "Çarpışma Önleme Sistemi",
      "Kablosuz Apple CarPlay",
      "Geniş Panoramik Tavan",
    ],
    location: "Izmir",
    isAvailable: true,
    averageRating: 4.2,
    totalReviews: 122,
    mileage: 44300,
    color: "Race Mavi",
    licensePlate: "35-SKD-23",
    carType: "Hatchback",
  },
  {
    make: "Mitsubishi",
    modelName: "Outlander PHEV",
    year: 2024,
    transmission: "Otomatik",
    fuelType: "Hibrit",
    seats: 7,
    doors: 5,
    pricePerDay: 2400,
    description:
      "Ailenizin hem çevreci hem de pratik yol arkadaşı. Mitsubishi Outlander PHEV; S-AWC süper dört tekerlekten çekiş ve üçüncü sıra koltuklarıyla çok yönlülüğü maksimize ediyor.",
    features: [
      "S-AWC Süper AWD",
      "Bose Ses Sistemi",
      "Panoramik Cam Tavan",
      "3. Sıra Koltuk",
      "MI-PILOT Otonom Sürüş Asistanı",
      "Gece Görüş Kamerası",
    ],
    location: "Antalya",
    isAvailable: true,
    averageRating: 4.3,
    totalReviews: 57,
    mileage: 22800,
    color: "Diamond White",
    licensePlate: "07-MTS-24",
    carType: "SUV",
  },
  {
    make: "Lexus",
    modelName: "LC 500",
    year: 2024,
    transmission: "Otomatik",
    fuelType: "Benzin",
    seats: 4,
    doors: 2,
    pricePerDay: 11000,
    description:
      "Japon otomobil sanatının zirvesi. Lexus LC 500; 477 beygirlik 5.0L V8 atmosferik motoru, el yapımı iç mekanı ve akustik mükemmelliğiyle otomobili bir müzik aletine dönüştürüyor.",
    features: [
      "5.0L V8 Atmosferik Motor",
      "Mark Levinson Ses Sistemi",
      "10 inç Head-Up Display",
      "Isıtmalı/Soğutmalı Koltuklar",
      "Lexus Safety System+",
      "Çift Renk İç Mekan",
    ],
    location: "Istanbul",
    isAvailable: true,
    averageRating: 4.8,
    totalReviews: 19,
    mileage: 7600,
    color: "Structural Blue",
    licensePlate: "34-LXS-24",
    carType: "Coupe",
  },
  {
    make: "Fiat",
    modelName: "500",
    year: 2023,
    transmission: "Otomatik",
    fuelType: "Elektrik",
    seats: 4,
    doors: 3,
    pricePerDay: 780,
    description:
      "Şehrin en sevimli ve çevreci arabası. Fiat 500e; tam elektrikli motor, retro ikonografisi ve kompakt boyutuyla İtalyan şıklığını günümüze taşıyor.",
    features: [
      "Tam Elektrikli Motor",
      "7 inç Dokunmatik Ekran",
      "Apple CarPlay",
      "Sürüş Modu Seçici",
      "Şarj Planlaması",
      "Geri Görüş Kamerası",
    ],
    location: "Izmir",
    isAvailable: true,
    averageRating: 4.0,
    totalReviews: 103,
    mileage: 17300,
    color: "Gelato Beyaz",
    licensePlate: "35-FIT-23",
    carType: "Hatchback",
  },
  {
    make: "Dodge",
    modelName: "Challenger Hellcat",
    year: 2023,
    transmission: "Otomatik",
    fuelType: "Benzin",
    seats: 5,
    doors: 2,
    pricePerDay: 8200,
    description:
      "Amerikan otomobil kültürünün en gürültülü ifadesi. Dodge Challenger Hellcat; 717 beygirlik süper şarjlı V8 ile arka tekerlekleri yakarak özgürlüğü haykırıyor.",
    features: [
      "6.2L Supercharged HEMI V8",
      "Launch Control",
      "Line Lock",
      "Harman Kardon Ses Sistemi",
      "SRT Drive Modes",
      "Brembo Frenler",
    ],
    location: "Miami",
    isAvailable: true,
    averageRating: 4.7,
    totalReviews: 61,
    mileage: 12400,
    color: "Hellraisin Mor",
    licensePlate: "FL-HELL7",
    carType: "Coupe",
  },
  {
    make: "Cadillac",
    modelName: "Escalade",
    year: 2024,
    transmission: "Otomatik",
    fuelType: "Benzin",
    seats: 8,
    doors: 5,
    pricePerDay: 8800,
    description:
      "Amerikan lüksünün en büyük ifadesi. Cadillac Escalade; devasa boyutu, 38 inç OLED gösterge paneli ve piyasanın en iyi AKG ses sistemiyle lüksü yeniden tanımlar.",
    features: [
      "38 inç Curved OLED Ekran",
      "AKG Studio Ses Sistemi",
      "Super Cruise Otonom Sürüş",
      "Hava Süspansiyonu",
      "Isıtmalı/Soğutmalı/Masaj Koltuklar",
      "Nightvision Kamera",
    ],
    location: "Miami",
    isAvailable: true,
    averageRating: 4.6,
    totalReviews: 43,
    mileage: 15600,
    color: "Black Raven",
    licensePlate: "FL-CAD24",
    carType: "SUV",
  },
  {
    make: "Alfa Romeo",
    modelName: "Stelvio Quadrifoglio",
    year: 2023,
    transmission: "Otomatik",
    fuelType: "Benzin",
    seats: 5,
    doors: 5,
    pricePerDay: 6500,
    description:
      "Dünyanın en hızlı SUV'u unvanını taşıyan İtalyan başyapıtı. Alfa Romeo Stelvio Quadrifoglio; 510 beygirlik twin-turbo V6 ve Ferrari'den gelen mühendislik DNAsıyla Nürburgring pistinde rekor kırdı.",
    features: [
      "Twin-Turbo Ferrari V6",
      "DNA Pro Sürüş Modları",
      "Karbon Seramik Frenler",
      "Şasi Entegre Vektörleme Frenler",
      "Harman Kardon Ses",
      "Alcantara Tavan",
    ],
    location: "Bodrum",
    isAvailable: true,
    averageRating: 4.8,
    totalReviews: 28,
    mileage: 13900,
    color: "Rosso Competizione",
    licensePlate: "48-ARQ-23",
    carType: "SUV",
  },
  {
    make: "Mazda",
    modelName: "MX-5",
    year: 2023,
    transmission: "Manuel",
    fuelType: "Benzin",
    seats: 2,
    doors: 2,
    pricePerDay: 1800,
    description:
      "Sürüş zevkini minimalist bir formda sunan roadster ikonu. Mazda MX-5; hafif yapısı, hassas direksiyon hissi ve üstü açılabilir tasarımıyla her virajı kutlamaya dönüştürüyor.",
    features: [
      "Açılabilir Soft Top",
      "Bose Ses Sistemi",
      "Bilstein Amortisörler",
      "Sürücü Odaklı Kokpit",
      "i-Activsense Güvenlik",
      "Isıtmalı Koltuklar",
    ],
    location: "Antalya",
    isAvailable: true,
    averageRating: 4.6,
    totalReviews: 79,
    mileage: 20100,
    color: "Soul Red Crystal",
    licensePlate: "07-MZD-23",
    carType: "Coupe",
  },
  {
    make: "Volkswagen",
    modelName: "ID.4",
    year: 2024,
    transmission: "Otomatik",
    fuelType: "Elektrik",
    seats: 5,
    doors: 5,
    pricePerDay: 2200,
    description:
      "Elektrikli mobiliteyi ana akıma taşıyan SUV. Volkswagen ID.4; geniş ve aydınlık iç mekanı, 520 km menzili ve ID. yazılım ekosistemiyle günlük kullanımda hiçbir taviz vermiyor.",
    features: [
      "ID. Software 3.5",
      "Augmented Reality HUD",
      "Travel Assist",
      "12 inç Dokunmatik Ekran",
      "Isıtmalı Ön Koltuklar",
      "Kablosuz Apple CarPlay",
    ],
    location: "Ankara",
    isAvailable: true,
    averageRating: 4.4,
    totalReviews: 86,
    mileage: 16700,
    color: "Moonstone Grey",
    licensePlate: "06-VWI-24",
    carType: "SUV",
  },
  {
    make: "Lamborghini",
    modelName: "Urus",
    year: 2024,
    transmission: "Otomatik",
    fuelType: "Benzin",
    seats: 5,
    doors: 5,
    pricePerDay: 24000,
    description:
      "Süper SUV kategorisini yaratan efsane. Lamborghini Urus; 666 beygirlik twin-turbo V8 ile 0-100 km/s'yi 3.3 saniyede geçen, hem yolda hem arazide baskın bir güç.",
    features: [
      "ANIMA Sürücü Modu Seçici",
      "Hava Süspansiyonu",
      "Bang & Olufsen 3D Ses",
      "Karbon Seramik Frenler",
      "Alcantara/Deri İç Mekan",
      "Lamborghini Telemetri",
    ],
    location: "Istanbul",
    isAvailable: true,
    averageRating: 4.9,
    totalReviews: 23,
    mileage: 8100,
    color: "Verde Mantis",
    licensePlate: "34-LBU-24",
    carType: "SUV",
  },
] as const;

async function main() {
  console.log("[seed] connecting to MongoDB...");
  await connectDB();

  console.log("[seed] clearing existing cars...");
  await Car.deleteMany({});

  console.log(`[seed] inserting ${cars.length} cars...`);
  const inserted = await Car.insertMany(cars);

  console.log("[seed] inserted ids:");
  for (const doc of inserted) {
    console.log(`  - ${doc._id} :: ${doc.make} ${doc.modelName}`);
  }

  console.log("[seed] done.");
  process.exit(0);
}

main().catch((err) => {
  console.error("[seed] failed:", err);
  process.exit(1);
});